### ISSUE TITLE
Iipa-tuura package creation (github)

### ISSUE THREAD

**Issue by Tiboris** [freeipa/ipa-tuura#38]
I am asking any owner of freeipa organization to enable packages for an [organization freeipa](https://github.com/organizations/freeipa/settings/packages) At this this page you should be able to enable public packages to be created at least for this project. It will help us to publish container images and use ghcr.io per pull rewuest to test changes and store containers.

**Comment by Tiboris** [comment]
Context: with this [PR ](https://github.com/freeipa/ipa-tuura/pull/37) i am trying to enable per pull request built for an image which can be reused in the workflow. See PRs in my fork to see workflow succeeding and packages with given labels to appear in repo.

**Comment by abbra** [comment]
I enabled public packages.

**Comment by Tiboris** [comment]
Thanks @abbra I have another error now:

Error: writing blob: initiating layer upload to /v2/freeipa/ipa-tuura/blobs/uploads/ in ghcr.io: denied: installation not allowed to Create organization package"

could you please check if it is allowed for actions to push new packages in the repo?

I hope this can help:
https://github.com/actions/runner/issues/1039#issuecomment-1465814873

**Comment by abbra** [comment]
I'll look on Monday. You should not do this, rather create packages at the repo level, not organization.

**Comment by abbra** [comment]
I checked properties and we allow read and write permissions by default in both the organization and the individual projects' settings. You need to check the token you generated to see if that one actually has write permission as well. Since this seems to be a personal token, I cannot help there.
