### ISSUE TITLE
realm join failing to AD domain

### ISSUE THREAD

**Issue by spoore1** [freeipa/ipa-tuura#68]
Adding an AD domain from Keycloak with the SCIM user storage plugin, it looks like the domain is properly added.   However, when I check on the ipa-tuura bridge container, SSSD isn't configured and I see errors in the journal for the realm join.

[bridge_ad_join2.log](https://github.com/freeipa/ipa-tuura/files/12771948/bridge_ad_join2.log)

**Comment by spoore1** [comment]
From a comparison with a manual `realm join ad.da.test`, it looks like the beginning of the realm log entries are the same until:

```
Sep 29 21:58:30 bridge.ipa.test realmd[925]:  * Successfully discovered: da.test
Sep 29 21:58:30 bridge.ipa.test realmd[925]: client gone away: :1.47
Sep 29 21:58:30 bridge.ipa.test realmd[925]: released daemon: :1.47
```

**Comment by antoniotorresm** [comment]
Which container image are you using?

**Comment by spoore1** [comment]
> Which container image are you using?

quay.io/ftrivino/bridge-fedora-devel
