### ISSUE TITLE
New AD users not seen in Keycloak

### ISSUE THREAD

**Issue by spoore1** [freeipa/ipa-tuura#72]
I am able to setup an Integration domain in Keycloak to an AD domain.   If I add a user in Keycloak, I see it replicated to AD.  However, if I add a new user in AD, I do not see it in Keycloak.

I will add more details soon.

**Comment by justin-stephenson** [comment]
I see the same issue here in IPA. The bridge service does not seem to pickup that the user was added on the backend directly.

**Comment by abbra** [comment]
This is a fundamental issue that cannot be easily fixed without watching changes on the backend with synchrepl or similar LDAP extension. I am not sure it is a problem we should solve, though.

Does the user added through the backend directly would appear in Keycloak if you'd try to authenticate as that user through Keycloak?

**Comment by justin-stephenson** [comment]
> Does the user added through the backend directly would appear in Keycloak if you'd try to authenticate as that user through Keycloak?

No, the first step of the authentication operation is for keycloak to send a `/Users/.search` endpoint request to find the user, which fails for the same reason.

If ipa-tuura could possibly provide an endpoint which triggers an internal refresh/reload of user data somehow, the keycloak plugin can send a request to that endpoint by implementing https://www.keycloak.org/docs/latest/server_development/#importsynchronization-interface

**Comment by abbra** [comment]
Ok, so there is actually a search happening, that's good. It means we can do a better logic on our side. If that user wasn't even known to ipa-tuura, then it was never cached and we should force a lookup against the backend. SSSD in this case should do a proper lookup.

**Comment by spoore1** [comment]
Ok, I cannot confirm this yet because my test environment is gone but, I'm almost certain that I had specific user lookups in Keycloak working and finding IPA users.   I got that working and then moved on to the AD tests and hit this.   Hence why for me I labeled it as an AD specific issue.   I will have to rebulid my test environment to reproduce this.

Now though while trying to test with the HTTPS changes in the works, I am not able to lookup an IPA user in Keycloak.   I'm still troubleshooting and will post more as soon as I can.

**Comment by justin-stephenson** [comment]
For the IPA case, we saw that the issue was in the SSSD infopipe logs.
~~~
   *  (2023-11-13 22:18:47): [ifp] [sbus_check_access] (0x0400): org.freedesktop.DBus.Introspectable.Introspect: permission denied for sender :1.123 with uid 48
~~~

Adding apache (uid 48) to the `allowed_uids` under the sssd.conf `[ifp]` section fixed this.

Scott will test with AD to see if it is still a problem or not.

**Comment by spoore1** [comment]
FYI, for IPA case, adding `allowed_uids` did resolve the issue.   I'm testing some things for AD that seemed to work now.  Will update with more info either later today or tomorrow.

**Comment by spoore1** [comment]
Ok, from my testing, it appears that `sssd.conf` needs `ldap_user_extra_attrs = sn:sn, givenname:givenname, mail:mail` in `[domain/]`  section as well as `allowed_uids = apache, sssd, root` in the `[ifp]` section.

When I add both using the latest container I am able to see AD users from a lookup on the Keycloak side.
```
# ./kc_get_user aduser3@da.test
[ {
  "id" : "ddedbae5-0d87-4b97-8f91-88bb237873a2",
  "createdTimestamp" : 1700061298980,
  "username" : "aduser3@da.test",
  "enabled" : true,
  "totp" : false,
  "emailVerified" : false,
  "firstName" : "NewUser3",
  "lastName" : "ADUser3",
  "email" : "aduser3@da.test",
  "federationLink" : "b6b19c92-ac94-4124-9f3c-65eb49d4071a",
  "disableableCredentialTypes" : [ ],
  "requiredActions" : [ ],
  "notBefore" : 0,
  "access" : {
    "manageGroupMembership" : true,
    "view" : true,
    "mapRoles" : true,
    "impersonate" : true,
    "manage" : true
  }
} ]
```

**Comment by spoore1** [comment]
Also note, that when I found a fix/workaround for the null errors for lookups from Keycloak that failed originally.   Clearing SSSD's cache after adding the `ldap_user_extra_attrs` option seemed to work.  I also had to restart both sssd and httpd on the container.   So far that seems to fix the issue.
