### ISSUE TITLE
unit tests: false failures related to changes to sssd.conf

### ISSUE THREAD

**Issue by antoniotorresm** [freeipa/ipa-tuura#77]
As found in https://github.com/freeipa/ipa-tuura/actions/runs/6889421416/job/18740387218?pr=76 , our current unit tests can produce false failures when testing changes to sssd.conf. This is most likely caused by not using a real environment. Manually testing the fix in an environment with actual deployments of IPA, LDAP and AD shows no errors.

**Comment by spoore1** [comment]
Could it be how the unit tests interact with sssd.conf?   Could we need another chmod workaround for the unit tests?  Or in the unit tests?   

Also, in my full env testing with the https container, it looks like I have to restart httpd in between deleting and adding new ntegration domains.   Could that affect the the unit tests?   Need a restart between adding domains?

**Comment by f-trivino** [comment]
> Could it be how the unit tests interact with sssd.conf? Could we need another chmod workaround for the unit tests? Or in the unit tests?
> 
> Also, in my full env testing with the https container, it looks like I have to restart httpd in between deleting and adding new ntegration domains. Could that affect the the unit tests? Need a restart between adding domains?

The unit tests are running on a github actions runner, the POST request to the domains app provokes a real enrollment with an AD domain, that doesn't exist. So we need to filter the test for now until we figure out a way how to run with --dry-run enabled.

**Comment by f-trivino** [comment]
POST unit test is skipped now until we figure out a way to implement mocks.
