### ISSUE TITLE
Enable CSRF protection for the creds app

### ISSUE THREAD

**Issue by f-trivino** [freeipa/ipa-tuura#81]
Enable CSRF protection for the [creds](https://github.com/freeipa/ipa-tuura/tree/main/src/ipa-tuura/creds) app, based on:

https://docs.djangoproject.com/en/1.8/ref/csrf/#how-it-works

Example from [keycloak plugin](https://github.com/justin-stephenson/scim-keycloak-user-storage-spi/): https://github.com/justin-stephenson/scim-keycloak-user-storage-spi/commit/5e201e59be9630ac0551b9d06509401d24740242

**Comment by f-trivino** [comment]
thanks @flo-renaud !!!, looks like changes are only needed in the keycloak plugin. @justin-stephenson will test and close this ticket if no issues.

**Comment by justin-stephenson** [comment]
Fix here https://github.com/justin-stephenson/scim-keycloak-user-storage-spi/pull/15 is working in my limited testing.

**Comment by f-trivino** [comment]
thank you @justin-stephenson , I'm closing this ticket.
